site_name: Sistemas Reativos
theme:     readthedocs
#site_dir:  site/v0.20

pages:
- Home: 'index.md'
- Arduino:
    - Componentes:
        - Entrada:
            - 'Botão de Pressão': 'arduino/componentes/entrada/botao-de-pressao.md'
        - Saída:
            - 'LED': 'arduino/componentes/saida/led.md'
