site_name: Arduino
theme:     readthedocs
#site_dir:  site/v0.20

pages:
    - Home:                         'index.md'
    - Componentes:
        - Componentes:              'componentes/index.md'
        - Entrada:
            #- 'Entrada':           'componentes/entrada/index.md'
            - 'Botão de Pressão':   'componentes/entrada/botao-de-pressao.md'
        - Saída:
            #- 'Saída':             'componentes/saida/index.md'
            - 'LED':                'componentes/saida/led.md'
        - Comunicação:
            - 'Serial':             'componentes/comunicacao/serial.md'
